{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.3.jar",
          "url": "spring-context-support-6.1.3.jar",
          "size": 174055,
          "sha512": "a3425308dba3f8b18dd698e895e73e381f2182f06d0b6a3cddde94da426929d2670477679e5da633b868412bc7c39b818af605e6d9f2bdf5bea927124c02edd5",
          "sha256": "40ad89072205dc20b1c13bd305ad290cdcf101f0bbb64bb9a03274606dfc722f",
          "sha1": "55ff73910c4851c37f6919a071453ddc40f7dc38",
          "md5": "b7a40dbdacbe1e473724b4c6139a3a33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.3.jar",
          "url": "spring-context-support-6.1.3.jar",
          "size": 174055,
          "sha512": "a3425308dba3f8b18dd698e895e73e381f2182f06d0b6a3cddde94da426929d2670477679e5da633b868412bc7c39b818af605e6d9f2bdf5bea927124c02edd5",
          "sha256": "40ad89072205dc20b1c13bd305ad290cdcf101f0bbb64bb9a03274606dfc722f",
          "sha1": "55ff73910c4851c37f6919a071453ddc40f7dc38",
          "md5": "b7a40dbdacbe1e473724b4c6139a3a33"
        }
      ]
    }
  ]
}
