{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.3.jar",
          "url": "spring-webflux-6.1.3.jar",
          "size": 967690,
          "sha512": "d17786381af04c82fcc367608b819b81ee35c8ccb1de4a5d2913d48069ddb11d666fd022849a94f653ae8723ce42e9986594780514014f2b1425ad143527fd5c",
          "sha256": "7ffe8421ebd14f20e02c092e770065130d1b350bd317c10f6ddf7a5b3fff6ca0",
          "sha1": "426447b8e64765db5c2901f2b33cdb691b845f34",
          "md5": "4698260d3ce121eed2c218b6db56f281"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.3.jar",
          "url": "spring-webflux-6.1.3.jar",
          "size": 967690,
          "sha512": "d17786381af04c82fcc367608b819b81ee35c8ccb1de4a5d2913d48069ddb11d666fd022849a94f653ae8723ce42e9986594780514014f2b1425ad143527fd5c",
          "sha256": "7ffe8421ebd14f20e02c092e770065130d1b350bd317c10f6ddf7a5b3fff6ca0",
          "sha1": "426447b8e64765db5c2901f2b33cdb691b845f34",
          "md5": "4698260d3ce121eed2c218b6db56f281"
        }
      ]
    }
  ]
}
