{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-oauth2-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "size": 4779,
          "sha512": "0109e0a6fa07f1c84ae48599d71cd835d2ff1a23b8997fe48d5f0336a959cbae14d9538000f6d2cfc63d17fd614ba955b7c51330c593e5a59aa5ed24b3e2d4da",
          "sha256": "320c3648f096a8bb6f035647669b72dc7be64b76249469ddbd032b2be5fb48da",
          "sha1": "cce33514a28968b4f6203cdcce700192d19b1ef0",
          "md5": "ec67b9f6312dcf9fd3a5d48e985d7e48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "size": 4779,
          "sha512": "0109e0a6fa07f1c84ae48599d71cd835d2ff1a23b8997fe48d5f0336a959cbae14d9538000f6d2cfc63d17fd614ba955b7c51330c593e5a59aa5ed24b3e2d4da",
          "sha256": "320c3648f096a8bb6f035647669b72dc7be64b76249469ddbd032b2be5fb48da",
          "sha1": "cce33514a28968b4f6203cdcce700192d19b1ef0",
          "md5": "ec67b9f6312dcf9fd3a5d48e985d7e48"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "size": 4779,
          "sha512": "0109e0a6fa07f1c84ae48599d71cd835d2ff1a23b8997fe48d5f0336a959cbae14d9538000f6d2cfc63d17fd614ba955b7c51330c593e5a59aa5ed24b3e2d4da",
          "sha256": "320c3648f096a8bb6f035647669b72dc7be64b76249469ddbd032b2be5fb48da",
          "sha1": "cce33514a28968b4f6203cdcce700192d19b1ef0",
          "md5": "ec67b9f6312dcf9fd3a5d48e985d7e48"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-oauth2-client-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2.jar",
          "size": 4779,
          "sha512": "0109e0a6fa07f1c84ae48599d71cd835d2ff1a23b8997fe48d5f0336a959cbae14d9538000f6d2cfc63d17fd614ba955b7c51330c593e5a59aa5ed24b3e2d4da",
          "sha256": "320c3648f096a8bb6f035647669b72dc7be64b76249469ddbd032b2be5fb48da",
          "sha1": "cce33514a28968b4f6203cdcce700192d19b1ef0",
          "md5": "ec67b9f6312dcf9fd3a5d48e985d7e48"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-oauth2-client-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2-javadoc.jar",
          "size": 4750,
          "sha512": "20e8e76018f121c7ab9c18ee68617e5df3b189fbbd1e0bcec2492244518e63550d116bad189125541c259245609bfe958be9c013c93c2aec0a1991f468470234",
          "sha256": "dfcecdbcfa50b96073b75672fed8f332239551d8f542b01ca8a8c5d74e033150",
          "sha1": "c3761be650fb2fc36fe45a19e34753b75ba69177",
          "md5": "d076f064a70ce5c1105eecd998165d57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.2.2-sources.jar",
          "url": "spring-boot-starter-oauth2-client-3.2.2-sources.jar",
          "size": 4748,
          "sha512": "f821dabdbdf3c0c4aeea7fc233e4841432f6ccb537ccc89515a39d354895c2e22379d4e6b884c2d14908ecab87b299a370024725383f21159ca4cbe73b07d83c",
          "sha256": "e9aad63c191ecf4f71faf02c908c4e11d91aec0c77444282f226d449ee6636a6",
          "sha1": "3f58fe777784e46858883ada989990d86f82a5d5",
          "md5": "e982993d3451c945206f4a45f58c0050"
        }
      ]
    }
  ]
}
