{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.3.jar",
          "url": "spring-oxm-6.1.3.jar",
          "size": 59806,
          "sha512": "67563f2d0fd9e15f271e2764013e843c29f7d45c25cb9cf7c431963971b9aeb4453b4510df6f1c98084bb740c5e4915b14e1bf0247acefd0e69842915d7e8885",
          "sha256": "81e99748b8577fa40df01dbeb98d2eafd4679c8bbb034256e9aff92113bcd5df",
          "sha1": "d651e85c2ea70411cea317b538bc6c713bc683fa",
          "md5": "bd7c574d973f36369f24289376780ed9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.3.jar",
          "url": "spring-oxm-6.1.3.jar",
          "size": 59806,
          "sha512": "67563f2d0fd9e15f271e2764013e843c29f7d45c25cb9cf7c431963971b9aeb4453b4510df6f1c98084bb740c5e4915b14e1bf0247acefd0e69842915d7e8885",
          "sha256": "81e99748b8577fa40df01dbeb98d2eafd4679c8bbb034256e9aff92113bcd5df",
          "sha1": "d651e85c2ea70411cea317b538bc6c713bc683fa",
          "md5": "bd7c574d973f36369f24289376780ed9"
        }
      ]
    }
  ]
}
