{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.2.jar",
          "url": "reactor-core-3.6.2.jar",
          "size": 1868014,
          "sha512": "33dfd13b5dd5e46f91f5eaa459d5dc80242aa79cd74bdc1be707653d511ed7bdb6d950fc49410a255190da75988c27426c0ef979fd33d46cf27ae3a58cad01fe",
          "sha256": "6e235f0be9732ebd6a42c585dfd53274065978bfbc28d721d7ecf487fde27b52",
          "sha1": "679ac38d031c154374182748491a177a76c890e1",
          "md5": "c7553524c90891b9adf11dda72356a96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.2.jar",
          "url": "reactor-core-3.6.2.jar",
          "size": 1868014,
          "sha512": "33dfd13b5dd5e46f91f5eaa459d5dc80242aa79cd74bdc1be707653d511ed7bdb6d950fc49410a255190da75988c27426c0ef979fd33d46cf27ae3a58cad01fe",
          "sha256": "6e235f0be9732ebd6a42c585dfd53274065978bfbc28d721d7ecf487fde27b52",
          "sha1": "679ac38d031c154374182748491a177a76c890e1",
          "md5": "c7553524c90891b9adf11dda72356a96"
        }
      ]
    }
  ]
}
