{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.3.1.jar",
          "url": "spring-security-crypto-6.3.1.jar",
          "size": 100188,
          "sha512": "adcd6a2b96bae5ab988698ce993bcb6d81adaa3998531f2da34fd8972f13d98611781759ec8dd5ec9fd1f879789f870c48cd2bee0b36b900c6801cf7abdf723b",
          "sha256": "3b5e284ba0455e08951bd30ce0d0def402f80514bfc874259cd389937706044b",
          "sha1": "3e66321782db499cca3884830188a091058121f3",
          "md5": "bb3ef3d1ad264c3492bb486c6236e9f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.3.1.jar",
          "url": "spring-security-crypto-6.3.1.jar",
          "size": 100188,
          "sha512": "adcd6a2b96bae5ab988698ce993bcb6d81adaa3998531f2da34fd8972f13d98611781759ec8dd5ec9fd1f879789f870c48cd2bee0b36b900c6801cf7abdf723b",
          "sha256": "3b5e284ba0455e08951bd30ce0d0def402f80514bfc874259cd389937706044b",
          "sha1": "3e66321782db499cca3884830188a091058121f3",
          "md5": "bb3ef3d1ad264c3492bb486c6236e9f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.3.1-javadoc.jar",
          "url": "spring-security-crypto-6.3.1-javadoc.jar",
          "size": 243264,
          "sha512": "7a49076050b9c0a14f53b3d4b54f4f71a0016644924d3b21bd0956a8c04bb9920cda4f9a4262ce009e449fd65251d794c48cf14646adcbf57e07bcad2477e55d",
          "sha256": "aa223d158e81380c01918f6057ba529b22e8210f188b1b6c66f00280ea4ed5d3",
          "sha1": "c86e43383f0bb5049b8bf27495eeef0f094b887c",
          "md5": "7ee4f70ede31931458c52e71cfa28fac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.3.1-sources.jar",
          "url": "spring-security-crypto-6.3.1-sources.jar",
          "size": 86477,
          "sha512": "182dcc9be907903d75dc2538b0c21a1e548a4e92ffd567a0991c31606a1eaad7c2428a76b7a59d298c7ad57b44194b5e09b9692fd3cd2e501489249f757a7078",
          "sha256": "acdaaff4c3e46507d7c5670f4b558b2ddd32badd815171ba8290db55cd720fcd",
          "sha1": "f440f08449797d5fb6e7750bf78817e870cb1b9c",
          "md5": "3940d1121a4b3d4e1a25c9790944bfdb"
        }
      ]
    }
  ]
}
