{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.3.2.jar",
          "url": "spring-boot-starter-webflux-3.3.2.jar",
          "size": 4787,
          "sha512": "bea7d9694ecf85e8ac3c91f74b679eb9e40d3ccd40e3c6312bca9b6dbe359a0141faef56e4f1d30d23358044d642b899206fbff9306c5479e1e11cd7cb8fca8b",
          "sha256": "330ebf3f7b73e3186998a7356f927e632efccdb95eb5b70938942626a4f33db0",
          "sha1": "f3b6893251df447a8e8a9ca4219f0b426b0aff91",
          "md5": "31fd1fb488d29ab434a49ac474a4fc99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.3.2.jar",
          "url": "spring-boot-starter-webflux-3.3.2.jar",
          "size": 4787,
          "sha512": "bea7d9694ecf85e8ac3c91f74b679eb9e40d3ccd40e3c6312bca9b6dbe359a0141faef56e4f1d30d23358044d642b899206fbff9306c5479e1e11cd7cb8fca8b",
          "sha256": "330ebf3f7b73e3186998a7356f927e632efccdb95eb5b70938942626a4f33db0",
          "sha1": "f3b6893251df447a8e8a9ca4219f0b426b0aff91",
          "md5": "31fd1fb488d29ab434a49ac474a4fc99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.3.2-javadoc.jar",
          "url": "spring-boot-starter-webflux-3.3.2-javadoc.jar",
          "size": 4744,
          "sha512": "27b7e8651fbe8e78716fb594b31efb4dc01661591fb29aab7c2d245733f457421aa50d49c7ee09be1681fb0799904d593a9e341d5a1523e5890a578ea7fa040b",
          "sha256": "4f58d4bc8ef8a23039aefa198428b90da67a8f57beb8b95f5be4a2175dcbc987",
          "sha1": "4af8457f84d2892cb2589dfea472f4a60b497dc8",
          "md5": "a651cf79d943a87359727477101bf562"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.3.2-sources.jar",
          "url": "spring-boot-starter-webflux-3.3.2-sources.jar",
          "size": 4743,
          "sha512": "a8dc111e15e680d159ef24a50511a920824c9b62273c493a062f41516588d2a3e46c5bee58925ea1f60bdaf13d72dfab98d0a6f681132f778552e9c784e30c45",
          "sha256": "a438ac416c662d901b2f90f4f2bc569ee7c4558d76927b4ffd12074b60d3e73d",
          "sha1": "9847f89836abdbfac107f5a934796eb04a0a5772",
          "md5": "cc4a714e1f6350aaf4224bc5f2f90a0f"
        }
      ]
    }
  ]
}
