{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis-reactive",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.1.RELEASE"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "size": 4794,
          "sha512": "af99058976a23b01f302469aa4294bb4265ad50b1ac2a194c60e5ead0b60a2b7c7474b435b9d6c4d7f80f76260cc127f8ac38cc21347d5008e05930eee98f59c",
          "sha256": "76fd3473cf018f36075ad7e2086c6ba6452640716b1999c457ba6939e01df3c5",
          "sha1": "4ef5d515e7a4ee5a7d2e387f916ff743f0ce1e59",
          "md5": "7deef7528deec11dbbbd62d9d421be2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.1.RELEASE"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "size": 4794,
          "sha512": "af99058976a23b01f302469aa4294bb4265ad50b1ac2a194c60e5ead0b60a2b7c7474b435b9d6c4d7f80f76260cc127f8ac38cc21347d5008e05930eee98f59c",
          "sha256": "76fd3473cf018f36075ad7e2086c6ba6452640716b1999c457ba6939e01df3c5",
          "sha1": "4ef5d515e7a4ee5a7d2e387f916ff743f0ce1e59",
          "md5": "7deef7528deec11dbbbd62d9d421be2f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "size": 4794,
          "sha512": "af99058976a23b01f302469aa4294bb4265ad50b1ac2a194c60e5ead0b60a2b7c7474b435b9d6c4d7f80f76260cc127f8ac38cc21347d5008e05930eee98f59c",
          "sha256": "76fd3473cf018f36075ad7e2086c6ba6452640716b1999c457ba6939e01df3c5",
          "sha1": "4ef5d515e7a4ee5a7d2e387f916ff743f0ce1e59",
          "md5": "7deef7528deec11dbbbd62d9d421be2f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-reactive-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2.jar",
          "size": 4794,
          "sha512": "af99058976a23b01f302469aa4294bb4265ad50b1ac2a194c60e5ead0b60a2b7c7474b435b9d6c4d7f80f76260cc127f8ac38cc21347d5008e05930eee98f59c",
          "sha256": "76fd3473cf018f36075ad7e2086c6ba6452640716b1999c457ba6939e01df3c5",
          "sha1": "4ef5d515e7a4ee5a7d2e387f916ff743f0ce1e59",
          "md5": "7deef7528deec11dbbbd62d9d421be2f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-reactive-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2-javadoc.jar",
          "size": 4757,
          "sha512": "33c6e0244bfdb3a5cd4d38c7cdedf5ff1c558b8753a172f0d4948991d97d2a63e3ea830f0f0175bcc3b954e02a8324b2ad3a8c55026f2676f6808f344cbdbb28",
          "sha256": "78fa282dd4335c2a2db09776352e7d9dea60444e85802a0160210f80505b0028",
          "sha1": "73861c10d913ffa7febf3fbbb18452c65a11cef8",
          "md5": "f92a3dd6ef6d6be1a866555a09c7c51f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-reactive-3.2.2-sources.jar",
          "url": "spring-boot-starter-data-redis-reactive-3.2.2-sources.jar",
          "size": 4755,
          "sha512": "a182bfad1b84f601384c03b6409ac2270d3e9957ca80c15debeb3d3a2a2abaaa555b8025bb81d436e56da1a5fe1f50c02f239bb5df4dc13709ca5a7d74226d75",
          "sha256": "2def0f47ffd70786dd1bba9da606f7b7ca64ea677fc98f598ce78a232d40f1d0",
          "sha1": "51cdae230b88a8c7b60906057f49853206202f76",
          "md5": "f8fcc1c3bc56acaebe4a091c1042deb3"
        }
      ]
    }
  ]
}
