server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-swallow-size: 10MB

logging:
  level:
    root: info
    org.springframework.data.mongodb: debug
    com.bubaum.bupay.admin.api: debug


  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"
    #    for dev
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%thread] %logger - %msg%n"
  file:
    name: ./logs/logback.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/logback_%d{yyyy-MM-dd}_%i.log
      max-history: 30
      max-file-size: 20MB


data:
  mongodb:
    uri: mongodb://ssddo:0524@cluster-shard-00-00.0mtmr.mongodb.net:27017,cluster-shard-00-01.0mtmr.mongodb.net:27017,cluster-shard-00-02.0mtmr.mongodb.net:27017/pulse?ssl=true&replicaSet=Cluster-shard-0&authSource=admin&retryWrites=true&w=majority&sslInvalidHostNameAllowed=true&tlsAllowInvalidCertificates=true
    auto-index-creation: true
  redis:


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
    disable-swagger-default-url: false
    display-request-duration: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: E1d4FPF9cL13/CnL5ko+ZUsQHazNLpwleboEmV/EeLeH68SXQPWF8k5wmGiihT+q4uVxuser75ftfuHgmWrXBfU6UhgXZrkV3mY=
  ## $ openssl rand -base64 74
  access-token:
    timeout: 24 # 1
    timeunit: HOURS
  refresh-token:
    timeout: 30 # 7
    timeunit: DAYS
    ## jwt.*.timeunit : MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
spring:
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    include: private
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      adjust-dates-to-context-time-zone: false
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0ff15f2cbe3c3db523d374e4be7595dd
            client-secret: x1Zug7Y0gLu2mDhPuE7HT5GbAQKAgLxg
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://13.209.104.215:8080/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            provider: kakao
          naver:
            client-id: NkW5Hoa0URcbkYWx_oIz
            client-secret: oXH2BRBtGg
            client-name: Naver
            authorization-grant-type: authorization_code
#            redirect-uri: "http://13.209.104.215:8080/login/naver/callback"
            redirect-uri: "http://pulse-dev.shop/auth/sign-up"
#            email-redirection-uri: "http://13.209.104.215:8080/login/naver/callEmail"
#            email-redirection-uri: "http://pulse-dev.shop/auth/find-password"
            scope: profile, email
            provider: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    region-name: ap-northeast-2
    bucket-name: pulse-api-dev

geocoding:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 0ff15f2cbe3c3db523d374e4be7595dd
#            client-secret: x1Zug7Y0gLu2mDhPuE7HT5GbAQKAgLxg
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"  # Spring Security 기본 경로 사용
#            scope: profile_nickname, account_email
#          naver:
#            client-id: 0ff15f2cbe3c3db523d374e4be7595dd
#            client-secret: x1Zug7Y0gLu2mDhPuE7HT5GbAQKAgLxg
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"  # Spring Security 기본 경로 사용
#            scope: profile_nickname, account_email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#
#naver:
#  client-id: NkW5Hoa0URcbkYWx_oIz
#  client-secret: oXH2BRBtGg
#  redirect-uri: http://localhost:8080/login/naver/callback
