server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
data:
  mongodb:
    url: mongodb://localhost:27017/pulse
    auto-index-creation: true
  redis:


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
    disable-swagger-default-url: false
    display-request-duration: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: E1d4FPF9cL13/CnL5ko+ZUsQHazNLpwleboEmV/EeLeH68SXQPWF8k5wmGiihT+q4uVxuser75ftfuHgmWrXBfU6UhgXZrkV3mY=
  ## $ openssl rand -base64 74
  access-token:
    timeout: 1
    timeunit: HOURS
  refresh-token:
    timeout: 7
    timeunit: DAYS
    ## jwt.*.timeunit : MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS

spring:
  main:
    web-application-type: reactive
  resources:
    cache:
      period: 0  # 리소스 캐시 비활성화