{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2.jar",
          "url": "spring-boot-starter-webflux-3.2.2.jar",
          "size": 4787,
          "sha512": "9cadd662de8d0831691dce8beae09c4eb9fc16a2ffec51792644703ff0ce1f83ca28a692cb739f2dcf3f952dc2b4741163588a510606681a3fa58652334f36e3",
          "sha256": "099fdbec6bbe997f34f32d3facc9342ed01a3a7493de81650f2a7ab3d5a486b2",
          "sha1": "25ae11864604f8f7b504b9feae710b859aed6464",
          "md5": "dc7b479fbdfd30245739588be937062b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2.jar",
          "url": "spring-boot-starter-webflux-3.2.2.jar",
          "size": 4787,
          "sha512": "9cadd662de8d0831691dce8beae09c4eb9fc16a2ffec51792644703ff0ce1f83ca28a692cb739f2dcf3f952dc2b4741163588a510606681a3fa58652334f36e3",
          "sha256": "099fdbec6bbe997f34f32d3facc9342ed01a3a7493de81650f2a7ab3d5a486b2",
          "sha1": "25ae11864604f8f7b504b9feae710b859aed6464",
          "md5": "dc7b479fbdfd30245739588be937062b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2.jar",
          "url": "spring-boot-starter-webflux-3.2.2.jar",
          "size": 4787,
          "sha512": "9cadd662de8d0831691dce8beae09c4eb9fc16a2ffec51792644703ff0ce1f83ca28a692cb739f2dcf3f952dc2b4741163588a510606681a3fa58652334f36e3",
          "sha256": "099fdbec6bbe997f34f32d3facc9342ed01a3a7493de81650f2a7ab3d5a486b2",
          "sha1": "25ae11864604f8f7b504b9feae710b859aed6464",
          "md5": "dc7b479fbdfd30245739588be937062b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-webflux-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2.jar",
          "url": "spring-boot-starter-webflux-3.2.2.jar",
          "size": 4787,
          "sha512": "9cadd662de8d0831691dce8beae09c4eb9fc16a2ffec51792644703ff0ce1f83ca28a692cb739f2dcf3f952dc2b4741163588a510606681a3fa58652334f36e3",
          "sha256": "099fdbec6bbe997f34f32d3facc9342ed01a3a7493de81650f2a7ab3d5a486b2",
          "sha1": "25ae11864604f8f7b504b9feae710b859aed6464",
          "md5": "dc7b479fbdfd30245739588be937062b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-webflux-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-webflux-3.2.2-javadoc.jar",
          "size": 4744,
          "sha512": "68087e46078815a477e4c6e8e5037f557be4c1e3ba70d3b696a7046c142e4fd680af87fd354a36fd9059a4a12cd61850e5ed60c81ed8e3976618cdfa317c6c9d",
          "sha256": "fe2506d92ae0e87fa82d5cf3463614d6ac1a37fbccce5a232f417c14271cb8e2",
          "sha1": "db1b35218b2cf44cfc1d28ed396dd9adfd9669ae",
          "md5": "4a39c6ec8520b6858379f7516c763da3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.2.2-sources.jar",
          "url": "spring-boot-starter-webflux-3.2.2-sources.jar",
          "size": 4743,
          "sha512": "6564580577ffab72fbdde536d8977617693f327588fe456932f9110e4d20d4391d6d3d6c487ccaaf11312c4748fcbdfe6777540cc6456e5f0a738c1716e1b7f6",
          "sha256": "63c519c160e22de50f653cc7c0e1c23a69f87a9b153151f6604906c19b9596d2",
          "sha1": "164a895e19008cc5b5757059018ae3a3584fc1f9",
          "md5": "8b11c7ef85dad02b715cb4755f6629b8"
        }
      ]
    }
  ]
}
