{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.1.11.jar",
          "url": "spring-web-6.1.11.jar",
          "size": 1896751,
          "sha512": "d02642e4a1715392be0b1d4e62f6b2e82d973cd6dba41019c62fb1a3630e60e8f6df91ebbe91ae15012f973cba9452d137a5ed404c9956cc2cf36a3bc1da16dd",
          "sha256": "db48c5feaae631a010177c1d72ebe9ad064cec38eab809c370382317aa99174b",
          "sha1": "08910d08f15492273543d2c8032b2b895e08ed9e",
          "md5": "25642932a93a9973aa42d89d79b0bff2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.1.11.jar",
          "url": "spring-web-6.1.11.jar",
          "size": 1896751,
          "sha512": "d02642e4a1715392be0b1d4e62f6b2e82d973cd6dba41019c62fb1a3630e60e8f6df91ebbe91ae15012f973cba9452d137a5ed404c9956cc2cf36a3bc1da16dd",
          "sha256": "db48c5feaae631a010177c1d72ebe9ad064cec38eab809c370382317aa99174b",
          "sha1": "08910d08f15492273543d2c8032b2b895e08ed9e",
          "md5": "25642932a93a9973aa42d89d79b0bff2"
        }
      ]
    }
  ]
}
