### Join
POST http://localhost:8080/api/v1/members/join
Content-Type: application/json

{
  "email": "neo@neo.com",
  "password": "1111",
  "phoneNumber": "01012345678",
  "birth": "19900101",
  "name": "neo",
  "nickName": "neo"
}


### Login
POST http://localhost:8080/api/v1/members/login
Content-Type: application/json

{
  "email": "neo@neo.com",
  "password": "1111"
}


### Join Room (Mentee)
@roomId = b1654280-ed48-4e7c-8c84-e45b030ad1d2
GET http://localhost:8080/api/v1/chats/join/{{roomId}}


### Room List
GET http://localhost:8080/api/v1/chats/list