### A
WEBSOCKET ws://localhost:8080/ws/v1/chat?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2N2M5ODBhZWFkNmRmNDI2N2QzNzk0OGUiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTc0MTI2ODM0NX0.YBFS08qWYIVmZ932B1XkyUy2b-q9dR_YFlGF9DqinFg