@expriedToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2N2M5ODBhZWFkNmRmNDI2N2QzNzk0OGUiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTc0MTI2ODM0NX0.YBFS08qWYIVmZ932B1XkyUy2b-q9dR_YFlGF9DqinFg
@correctToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2N2M5ODBhZWFkNmRmNDI2N2QzNzk0OGUiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTc0MTM3NzEyM30.Isspa6i8d44cxrldgkcF5EKqk0GAox9oM3zHzBYkjRk

### Normal
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}


### Expired token in queryString --Disconnect
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{expriedToken}}


### Wrong field
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}
Content-Type: application/json

{
  "wrong": "field"
}


### Wrong type
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}
Content-Type: application/json

{
  "message_type": "PONG"
}


### Expired token in message
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}
Content-Type: application/json

{
  "message_type": "PING",
  "room_id": null,
  "payload": "{{expriedToken}}"
}


### Correct PING
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}
Content-Type: application/json

{
  "message_type": "PING",
  "room_id": null,
  "payload": "{{correctToken}}"
}


### Correct TEXT
WEBSOCKET ws://localhost:8080/ws/v1/chat?token={{correctToken}}
Content-Type: application/json

{
  "message_type": "TEXT",
  "room_id": "1",
  "payload": "Hello, Nice to meet you!"
}


