{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "6.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.11.jar",
          "url": "spring-webflux-6.1.11.jar",
          "size": 979170,
          "sha512": "e86eb916a6434931cd07b46679f4063691f531607073fb75284f623db4219368cc55a5672f00ecfa0e4437ea66889e61c29c4e438afb2dfa062123621652e5be",
          "sha256": "510bf157d78e6aa4afb0cf4c54296196348f8a5fe1b63f32f4f189f73c8f075c",
          "sha1": "c1c1524026047fd9aed0c52d76e65c0ae9b46396",
          "md5": "d3111127c2cb6f5cd1a196af0addbc4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.11.jar",
          "url": "spring-webflux-6.1.11.jar",
          "size": 979170,
          "sha512": "e86eb916a6434931cd07b46679f4063691f531607073fb75284f623db4219368cc55a5672f00ecfa0e4437ea66889e61c29c4e438afb2dfa062123621652e5be",
          "sha256": "510bf157d78e6aa4afb0cf4c54296196348f8a5fe1b63f32f4f189f73c8f075c",
          "sha1": "c1c1524026047fd9aed0c52d76e65c0ae9b46396",
          "md5": "d3111127c2cb6f5cd1a196af0addbc4e"
        }
      ]
    }
  ]
}
