{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.1.3.jar",
          "url": "spring-test-6.1.3.jar",
          "size": 854157,
          "sha512": "45ad1040e3226f6671e56b28a90ec80fa7a919f5986a3a496cb8b3c41e5778748cc901818ba0b008eab03eee880c5a9b9fe1c711b5bd174233db1dc510801463",
          "sha256": "523adc94bd9193ddf4ff952a2f4f0c9dfa62217adbbcb2d192423517612e8adf",
          "sha1": "193a0c6c53a4eed98a1d7567e952647a92cf53aa",
          "md5": "bf584051d4e077ffbf0cbfbf7151afb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.1.3.jar",
          "url": "spring-test-6.1.3.jar",
          "size": 854157,
          "sha512": "45ad1040e3226f6671e56b28a90ec80fa7a919f5986a3a496cb8b3c41e5778748cc901818ba0b008eab03eee880c5a9b9fe1c711b5bd174233db1dc510801463",
          "sha256": "523adc94bd9193ddf4ff952a2f4f0c9dfa62217adbbcb2d192423517612e8adf",
          "sha1": "193a0c6c53a4eed98a1d7567e952647a92cf53aa",
          "md5": "bf584051d4e077ffbf0cbfbf7151afb2"
        }
      ]
    }
  ]
}
