{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.11.jar",
          "url": "spring-oxm-6.1.11.jar",
          "size": 59962,
          "sha512": "72895c40b30b9cf21b870550f9ec3a47c19d931c4ae53e3f6379df9193ab446db8134837fdc911d3f73001cf90c186ffb24d50d607adc6ec95173ad62000bb21",
          "sha256": "a9cb7d24a965235bf287113c5873cbb87db60637eb558e5a11c9a3ddcf359fa4",
          "sha1": "2825740197db37901d09b91704e1be3575a237c1",
          "md5": "dc057764325665189764e760ae455973"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.11.jar",
          "url": "spring-oxm-6.1.11.jar",
          "size": 59962,
          "sha512": "72895c40b30b9cf21b870550f9ec3a47c19d931c4ae53e3f6379df9193ab446db8134837fdc911d3f73001cf90c186ffb24d50d607adc6ec95173ad62000bb21",
          "sha256": "a9cb7d24a965235bf287113c5873cbb87db60637eb558e5a11c9a3ddcf359fa4",
          "sha1": "2825740197db37901d09b91704e1be3575a237c1",
          "md5": "dc057764325665189764e760ae455973"
        }
      ]
    }
  ]
}
