{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-core",
    "version": "6.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.3.1.jar",
          "url": "spring-security-oauth2-core-6.3.1.jar",
          "size": 105001,
          "sha512": "5578c7b7c23cd2571a9fccb372ae8e8a6c1f17a5ffa29c92a3f7ef0a90893f9736f690e89b1f191d4de402f802a1635953c6ef1d25a5d18e519163805c0ea979",
          "sha256": "ab75fde137655d904c585149ef6dcdcb588d0ca3cae47530de7f96a17e9d01f9",
          "sha1": "2f68a3b5a10022599b72430eb89bde5e6630975c",
          "md5": "9845d69ffa979a4c31eafda2b823f7d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.3.1.jar",
          "url": "spring-security-oauth2-core-6.3.1.jar",
          "size": 105001,
          "sha512": "5578c7b7c23cd2571a9fccb372ae8e8a6c1f17a5ffa29c92a3f7ef0a90893f9736f690e89b1f191d4de402f802a1635953c6ef1d25a5d18e519163805c0ea979",
          "sha256": "ab75fde137655d904c585149ef6dcdcb588d0ca3cae47530de7f96a17e9d01f9",
          "sha1": "2f68a3b5a10022599b72430eb89bde5e6630975c",
          "md5": "9845d69ffa979a4c31eafda2b823f7d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.3.1-javadoc.jar",
          "url": "spring-security-oauth2-core-6.3.1-javadoc.jar",
          "size": 360967,
          "sha512": "fa7967960f40d557fddab5d842d32227a615f0abee74db4136361abba1aed09792589e088605f12a41554821652dbcfcd8c26fd213c9f616bee73aae8f0b4147",
          "sha256": "f30c009f3dcbec016718228831e7c60663e5a0f58cc3a4a421c4783907bc927e",
          "sha1": "a0e0dad93e1bc71fa8d846b1a66d2c748b61e57b",
          "md5": "ced9daaa08919353bf5b9d5fd10b057a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.3.1-sources.jar",
          "url": "spring-security-oauth2-core-6.3.1-sources.jar",
          "size": 99435,
          "sha512": "7e6faae8b92512acb5567bfe2f7082609e483abd29f1dc7ed09fde4f4a58f56efcacd3623f402d649af11db95223422e2b4814701c9a35dc787a50670f38e694",
          "sha256": "eedfda075717f6038fac8bd340bd268bd8cd5ad34a58db64d8f058d56b28f849",
          "sha1": "714f1fe7ae270a49bacab0d33fd49c3095ec3056",
          "md5": "31ffd956e0c84a7a8144cd8f8702e98f"
        }
      ]
    }
  ]
}
