{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.8.jar",
          "url": "reactor-core-3.6.8.jar",
          "size": 1875226,
          "sha512": "25fcfb3f9a0fcde092e29157dab11eec52153f00779ab169eda4b5d16ea8e79a674365601ab7972a22099eb06f426bc9943f7316b438e55b0d9254d3a5851a7b",
          "sha256": "d06d49d0f09eeadf1a1d15c53fce0b74f9e219d728f8c47794f08b6e71029579",
          "sha1": "f3d0192db20e929d5a6552990269ae2993a93a58",
          "md5": "5b58fe9c1e133e96562688682247dafe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.8.jar",
          "url": "reactor-core-3.6.8.jar",
          "size": 1875226,
          "sha512": "25fcfb3f9a0fcde092e29157dab11eec52153f00779ab169eda4b5d16ea8e79a674365601ab7972a22099eb06f426bc9943f7316b438e55b0d9254d3a5851a7b",
          "sha256": "d06d49d0f09eeadf1a1d15c53fce0b74f9e219d728f8c47794f08b6e71029579",
          "sha1": "f3d0192db20e929d5a6552990269ae2993a93a58",
          "md5": "5b58fe9c1e133e96562688682247dafe"
        }
      ]
    }
  ]
}
