{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.3.1.jar",
          "url": "spring-security-web-6.3.1.jar",
          "size": 804080,
          "sha512": "b0a8e90d4f87077b507cbc291157ec38f028a744eb99d41cb30914bf76ed805c8008066deb8d1ad3f16d77fa0823c5309f6c0715ed041f27aeb6bb22e864ca8b",
          "sha256": "18681ae47e6529c61a1ca891997aac190bde0b9ee10b2776436f0ac392f470f4",
          "sha1": "aff43933f28c808252b2d31f768b92fa61b634f6",
          "md5": "6eb8c207f55dbd25496c349895e2888c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.3.1.jar",
          "url": "spring-security-web-6.3.1.jar",
          "size": 804080,
          "sha512": "b0a8e90d4f87077b507cbc291157ec38f028a744eb99d41cb30914bf76ed805c8008066deb8d1ad3f16d77fa0823c5309f6c0715ed041f27aeb6bb22e864ca8b",
          "sha256": "18681ae47e6529c61a1ca891997aac190bde0b9ee10b2776436f0ac392f470f4",
          "sha1": "aff43933f28c808252b2d31f768b92fa61b634f6",
          "md5": "6eb8c207f55dbd25496c349895e2888c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.3.1-javadoc.jar",
          "url": "spring-security-web-6.3.1-javadoc.jar",
          "size": 1846687,
          "sha512": "70c0d0db47941416fe72cd0ed9d81b1e400ff5e371f7a68761082b7a51a55f7dbb48d7c8adda96260378bcd22e087309e84a3f968f50bbeba11b58c9993c9b79",
          "sha256": "682cf39fcd01d3d4af031981f5d9ff249c7d2857cb8df7375b654c3d8390f132",
          "sha1": "e70fd10879a1098f8f8bb6d65ab39944babd8bb5",
          "md5": "9daac6d2497aa85ddf830c70777b3b2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.3.1-sources.jar",
          "url": "spring-security-web-6.3.1-sources.jar",
          "size": 662399,
          "sha512": "d9fbb1b205db46b6a0022b73c93f07d470e5195930997a91d73d3e6f803fa9a7e751aba846223034fd93561f62e8dbd47a1328be920c4944d3ba6c252fc5e562",
          "sha256": "1be6b0c3d55e3f42cc2cc4da0fbada0f56ce5b5c35b63d97584b1ed6bca74c27",
          "sha1": "80340dc1bdde9b174d17bcf766378572e766b303",
          "md5": "cbeaa5a20daf95cc15160a41d141a43f"
        }
      ]
    }
  ]
}
