{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-core",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.2.1.jar",
          "url": "spring-security-oauth2-core-6.2.1.jar",
          "size": 104565,
          "sha512": "40b117404353656787e2583c1b0d27aa174badc5227cb6056c54a31e90b0abad38f02b6c20467af7d6b1bf36f31bdde546a1648c64d0062eef6e3ee5fd64173b",
          "sha256": "f2a51080d32057d377d55c495e9023117e4195c630013a55d3bc41009ade3bcc",
          "sha1": "1927cdcddce10f1f852e25ed3445e1f1b96c17ad",
          "md5": "e11301ac4f49967381368a61f4aaa2c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-6.2.1.jar",
          "url": "spring-security-oauth2-core-6.2.1.jar",
          "size": 104565,
          "sha512": "40b117404353656787e2583c1b0d27aa174badc5227cb6056c54a31e90b0abad38f02b6c20467af7d6b1bf36f31bdde546a1648c64d0062eef6e3ee5fd64173b",
          "sha256": "f2a51080d32057d377d55c495e9023117e4195c630013a55d3bc41009ade3bcc",
          "sha1": "1927cdcddce10f1f852e25ed3445e1f1b96c17ad",
          "md5": "e11301ac4f49967381368a61f4aaa2c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.2.1-javadoc.jar",
          "url": "spring-security-oauth2-core-6.2.1-javadoc.jar",
          "size": 359491,
          "sha512": "3ec73e1524583c7140095edef5e1d0991e5b3ab7fcf035f18b627fb5ace202e86342da0d0a05bbe12e1767db2102765b487dfe6f8725a94047a09112fb12b82b",
          "sha256": "f220516bb6723486fa3c72d3cc3ad97fc0da508bebcf87139bb8331abc29623f",
          "sha1": "f8ab1b0e78bd3d6ead86bd56999ff791b2b3ef5d",
          "md5": "eef3ee85ccd10b09e6119193662f1e00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-6.2.1-sources.jar",
          "url": "spring-security-oauth2-core-6.2.1-sources.jar",
          "size": 99007,
          "sha512": "50b0ec3b205ddc42c825ee6c574f2b2df021f1533627b7c22d5d6c5342d8d1e7f8a78461ac5e51343867055a857dc7cc458ba4f5ccc9885e413990403b9cbb06",
          "sha256": "f8be8f2d2462125a6c5d541876e9a1752dfbbedbf1a8b79576693fdd97086718",
          "sha1": "9fefa3288ce11be9f0ace023dd91f4b784cb31f4",
          "md5": "b08ab8b81d1eaa31e771a5542e801fca"
        }
      ]
    }
  ]
}
