{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.3.jar",
          "url": "jackson-dataformat-yaml-2.15.3.jar",
          "size": 53492,
          "sha512": "3c2ebe108747b7e975a48430b37ec1f44e7cfe09281ccf9df273e0ea567c015dd573630038d8ce49363780c931175316996c04bfd16e26f3368a8e481da87f1f",
          "sha256": "d3ce08259e0c385ead479e46a21324ad1a759d14fd1154543b6148e36e172752",
          "sha1": "ecd237271773f75efdb09fd1c7594aed0cf31ec1",
          "md5": "28f0d0e0cb34e9ffe7f6345064572b16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.3.jar",
          "url": "jackson-dataformat-yaml-2.15.3.jar",
          "size": 53492,
          "sha512": "3c2ebe108747b7e975a48430b37ec1f44e7cfe09281ccf9df273e0ea567c015dd573630038d8ce49363780c931175316996c04bfd16e26f3368a8e481da87f1f",
          "sha256": "d3ce08259e0c385ead479e46a21324ad1a759d14fd1154543b6148e36e172752",
          "sha1": "ecd237271773f75efdb09fd1c7594aed0cf31ec1",
          "md5": "28f0d0e0cb34e9ffe7f6345064572b16"
        }
      ]
    }
  ]
}
