name: pulse
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clear Gradle cache
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trelloServer
          path: build/libs/back-0.0.1-SNAPSHOT.jar
          if-no-files-found: error  # 파일이 없으면 실패하도록 설정
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: trelloServer
          path: build/libs/
      - name: Cleanup old artifacts
        run: gh run list --limit 100 --json artifacts | jq -r '.[] | .artifacts[] | select(.expired == true) | .id' | xargs -I{} gh artifact delete {} --confirm
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: trelloServer
          path: build/libs/
      # Deploy to EC2 부분 수정
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # JAR 파일 전송
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/back-0.0.1-SNAPSHOT.jar ec2-user@13.209.104.215:/home/ec2-user/back-0.0.1-SNAPSHOT.jar
          
          # systemd 서비스 파일 생성
          cat > pulse-app.service << EOF
          [Unit]
          Description=Pulse Spring Boot Application
          After=network.target
          
          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user
          ExecStart=/usr/bin/java --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED -jar /home/ec2-user/back-0.0.1-SNAPSHOT.jar --geocoding.client-id=${{ secrets.NAVER_CLIENT_ID }} --geocoding.client-secret=${{ secrets.NAVER_CLIENT_SECRET }} --aws.access-key=${{ secrets.AWS_ACCESS_KEY }} --aws.secret-key=${{ secrets.AWS_SECRET_KEY }}
          SuccessExitStatus=143
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # 서비스 파일 전송 및 설치
          scp -i private_key.pem -o StrictHostKeyChecking=no pulse-app.service ec2-user@13.209.104.215:/home/ec2-user/pulse-app.service
          
          # systemd 서비스 설치 및 시작
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@13.209.104.215 "
            # 기존 프로세스 종료
            pgrep java | xargs kill -9 || true
            
            # 서비스 파일 설치
            sudo mv /home/ec2-user/pulse-app.service /etc/systemd/system/
            
            # systemd 재로드 및 서비스 시작
            sudo systemctl daemon-reload
            sudo systemctl enable pulse-app
            sudo systemctl restart pulse-app
            
            # 상태 확인
            sleep 5
            sudo systemctl status pulse-app
            journalctl -u pulse-app -n 20
          "
          
          # 임시 파일 정리
          rm -f private_key.pem
